### ISSUE TITLE
Add all default error types

### ISSUE THREAD

**Issue by RangerMauve** [Trott/eslint-plugin-new-with-error#1]
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) has a list of the different error types that come out of the box with the language. It might make sense to handle all of them by default.

**Comment by Trott** [comment]
I'm surprised that all those error types (except `InternalError` which MDN flags anyway) are in Node.js. So, yeah, this would probably make a lot of sense.

**Comment by RangerMauve** [comment]
I've only ever really used `TypeError`

**Comment by Trott** [comment]
Done in 9886ec0c688086e6b7f134970b34332e67721578 and published in v1.1.0.

**Comment by RangerMauve** [comment]
Sick!
