### ISSUE TITLE
Enable the plugin in `eslintrc`

### ISSUE THREAD

**Issue by kq2** [Trott/eslint-plugin-new-with-error#2]
How can I enable this plugin? I have installed it in `devDependencies` and added it to `plugins` in `eslintrc`, but still cannot see the warnings.
```
  plugins: ['new-with-error'],
```

**Comment by Trott** [comment]
You also need to enable the rule with a configuration option:

```
rules:
  new-with-error: 2
```

(Feel free to submit a PR adding this information to the `README` file!)
